Repository dragondrop-cloud/cloud-concierge, pull requests merged in 2023-09, with the labels that each got.

#49 Support cloud perch table of cloud actor identifications & Clean-Up
  .github/workflows/ci.yml
  main/.go-version
  main/Dockerfile
  main/go.mod
  main/go.sum
  main/internal/hclcreate/transfer_hcl.go
  main/internal/hclcreate/transfer_hcl_test.go
  main/internal/implementations/dragon_drop/cloud_perch_processing.go
  main/internal/implementations/dragon_drop/cloud_perch_processing_test.go
  main/internal/implementations/dragon_drop/http_dragondrop_managed_visualization.go
  main/internal/implementations/identify_cloud_actors/aws_log_querier.go
  main/internal/implementations/identify_cloud_actors/aws_log_querier_test.go
  main/internal/implementations/identify_cloud_actors/google_log_querier.go
  main/internal/implementations/identify_cloud_actors/google_log_querier_test.go
  main/internal/implementations/identify_cloud_actors/identify_cloud_actors.go
  main/internal/implementations/identify_cloud_actors/identify_cloud_actors_test.go
  main/internal/implementations/terraform_value_objects/cloud_actors_value_objects.go
Labels: new feature

#61 Pull NLP Script into Separate Google Function Service
  .github/workflows/ci.yml
  .github/workflows/nlpengine-cd.yml
  .github/workflows/nlpengine-ci.yml
  docker-compose.yml
  nlpengine/__init__.py
  nlpengine/main.py
  nlpengine/pytest-dockerfile
  nlpengine/requirements.txt
  nlpengine/tests/.coveragerc
  nlpengine/tests/__init__.py
  nlpengine/tests/test_main.py
Labels: enhancement

#62 Bugfix: github actions for nlp engine configuration
  .github/workflows/nlpengine-cd.yml
  .github/workflows/nlpengine-ci.yml
Labels: bug

#63 Integrate container execution with NLPEngine Endpoint
  .github/workflows/nlpengine-cd.yml
  .github/workflows/nlpengine-ci.yml
  main/internal/implementations/dragon_drop/http_dragondrop_client.go
  main/internal/implementations/dragon_drop/http_dragondrop_oss_methods.go
  main/internal/implementations/dragon_drop/isolated.go
  main/internal/implementations/resources_calculator/factory.go
  main/internal/implementations/resources_calculator/terraform_resources_calculator.go
  main/internal/interfaces/dragon_drop.go
  main/internal/pyscriptexec/executepyscript.go
  main/internal/pyscriptexec/pyscriptexec.go
  main/internal/python_scripts/nlpengine/main.py
  main/internal/python_scripts/requirements.txt
  main/internal/python_scripts/tests/nlpengine/__init__.py
  main/internal/python_scripts/tests/nlpengine/test_main.py
  main/job_config.go
  nlpengine/main.py
Labels: enhancement

#64 Integrate cloud-concierge container with remote NLPEngine Endpoint
  .github/workflows/nlpengine-cd.yml
  main/internal/implementations/dragon_drop/http_dragondrop_oss_methods.go
  main/internal/implementations/identify_cloud_actors/log_querier.go
  main/internal/implementations/terraform_import_migration_generator/terraform_import.go
  main/internal/python_scripts/nlpengine/__init__.py
  main/internal/python_scripts/nlpengine/main.py
Labels: enhancement

#65 2023/09/09 Dev --> Prod
  .github/workflows/ci.yml
  .github/workflows/nlpengine-cd.yml
  .github/workflows/nlpengine-ci.yml
  docker-compose.yml
  main/internal/implementations/dragon_drop/http_dragondrop_client.go
  main/internal/implementations/dragon_drop/http_dragondrop_oss_methods.go
  main/internal/implementations/dragon_drop/isolated.go
  main/internal/implementations/identify_cloud_actors/log_querier.go
  main/internal/implementations/resources_calculator/factory.go
  main/internal/implementations/resources_calculator/terraform_resources_calculator.go
  main/internal/implementations/terraform_import_migration_generator/terraform_import.go
  main/internal/interfaces/dragon_drop.go
  main/internal/pyscriptexec/executepyscript.go
  main/internal/pyscriptexec/pyscriptexec.go
  main/internal/python_scripts/requirements.txt
  main/job_config.go
  main/job_config_inferred.go
  nlpengine/__init__.py
  nlpengine/main.py
  nlpengine/pytest-dockerfile
  nlpengine/requirements.txt
  nlpengine/tests/.coveragerc
  nlpengine/tests/__init__.py
  nlpengine/tests/test_main.py
Labels: release

#68 Eliminate manual user specification of Infracost token
  docker-compose.yml
  main/go.mod
  main/go.sum
  main/internal/implementations/cost_estimation/cost_estimation.go
  main/internal/implementations/cost_estimation/isolated.go
  main/internal/implementations/dragon_drop/http_dragondrop_managed_execution.go
  main/internal/implementations/dragon_drop/http_dragondrop_oss_methods.go
  main/internal/implementations/dragon_drop/isolated.go
  main/internal/interfaces/cost_estimation.go
  main/internal/interfaces/dragon_drop.go
  main/job.go
  main/job_config.go
  main/job_config_test.go
  main/job_test.go
Labels: enhancement

#70 Replace AWS CLI with Go sdk
  .dockerignore
  README.md
  main/Dockerfile
  main/__init__.py
  main/internal/__init__.py
  main/internal/implementations/identify_cloud_actors/aws_log_querier.go
  main/internal/implementations/identify_cloud_actors/aws_log_querier_test.go
  main/internal/implementations/identify_cloud_actors/log_querier.go
  main/internal/python_scripts/__init__.py
  main/internal/python_scripts/requirements.txt
Labels: enhancement

#72 Replace gcloud CLI with Go SDK
  main/.dockerignore
  main/Dockerfile
  main/internal/documentize/new_resources.go
  main/internal/documentize/state_to_document.go
  main/internal/hclcreate/cost_estimation_helpers.go
  main/internal/hclcreate/transfer_hcl.go
  main/internal/hclcreate/write_import_blocks.go
  main/internal/hclcreate/write_tfmigrate.go
  main/internal/implementations/cost_estimation/cost_estimation.go
  main/internal/implementations/cost_estimation/infracost_data_extraction.go
  main/internal/implementations/identify_cloud_actors/google_log_querier.go
  main/internal/implementations/markdowncreation/costs_estimates.go
  main/internal/implementations/markdowncreation/costs_estimates_test.go
  main/internal/implementations/markdowncreation/markdown_creator.go
  main/internal/implementations/markdowncreation/security_risks.go
  main/internal/implementations/terraform_import_migration_generator/generic_import_generator.go
  main/internal/implementations/terraform_import_migration_generator/terraform_import.go
  main/internal/implementations/terraform_managed_resources_drift_detector/drift_detector/files_reader.go
  main/internal/implementations/terraform_managed_resources_drift_detector/drift_detector/terraform_managed_resources_drift_detector.go
  main/internal/implementations/terraform_security/tfsec.go
  main/internal/implementations/terraform_workspace/search_repo_workspaces.go
  main/internal/implementations/terraform_workspace/terraform_cloud.go
  main/internal/implementations/terraformer_executor/terraformer_cli/terraformer_executor.go
Labels: enhancement

#75 Update Docs to reflect usage of dragondrop-hosted infracost pricing API
  README.md
  examples/environments/aws-example.env
  examples/environments/azure-example.env
  examples/environments/gcp-example.env
Labels: documentation

#76 Add new resources table costs
  docker-compose.yml
  main/internal/implementations/markdowncreation/costs_estimates.go
  main/internal/implementations/markdowncreation/resources_managed_terraform_test.go
  main/internal/implementations/markdowncreation/resources_outside_terraform_control.go
  main/internal/implementations/markdowncreation/resources_outside_terraform_control_test.go
Labels: bug

#79 2023-09-22 Dev --> Prod
  .github/workflows/ci.yml
  README.md
  docker-compose.yml
  examples/environments/aws-example.env
  examples/environments/azure-example.env
  examples/environments/gcp-example.env
  main/go.mod
  main/go.sum
  main/internal/implementations/markdowncreation/costs_estimates.go
  main/internal/implementations/markdowncreation/resources_managed_terraform_test.go
  main/internal/implementations/markdowncreation/resources_outside_terraform_control.go
  main/internal/implementations/markdowncreation/resources_outside_terraform_control_test.go
  main/job_test.go
  main/main.go
  main/version_checker.go
  main/version_checker_test.go
  nlpengine/README.md
Labels: release
